VisualRust.Setup/racer.wxs
Previous PR updated builtin racer, which in turn removed some files. Setup script was still was referencing those (now  missing files) files. This commit fixes that oversight.
=> Fix installer

VisualRust.Build/Rustc.cs, VisualRust.Build/RustcParsedMessage.cs
Add parsing of `help: ` messages
=> Update rustc output parsing

VisualRust.Project/RustConfigProvider.cs
I'm not 100% sure how it will interact with cargo. I'm putting it on hold until we get cargo support, instead of shipping something that we might end up scrapping and reworking soon.
=> Disable support for custom project platforms/configurations

VisualRust/RustCommentSelectionCommandHandler.cs, VisualRust/RustCompletionCommandHandler.cs, VisualRust/RustDocumentListener.cs, VisualRust/RustF1HelpCommandHandler.cs, VisualRust/Utils.cs, VisualRust/VSCommandTarget.cs, VisualRust/VisualRust.csproj, VisualRust/VisualRustPackage.cs
This adresses #95 and #96, but the former is only rudimentarily implemented (I left quite a few `TODO` notes there). I also refactored RustCompletionCommandHandler to use the same helper class as the new commands, which I borrowed from [SassyStudio](https://github.com/darrenkopp/SassyStudio/blob/master/SassyStudio.2012/VSCommandTarget.cs).
=> Handle Un-/Comment and F1 commands in editor

VisualRust/Utils.cs
This fixes a crash on seeing the `?` character (as in `?Sized`)
=> Add missing token translations

VisualRust/RustCompletionSource.cs
- Fake empty ident token for completion at end of line
- Use Distinct() on racer MATCH output to avoid duplicates (e.g. racer issue 238)
- Use empty string instead of null for icon automation text to avoid a WPF error for each item.
=> Improvements to autocompletion

VisualRust/RustClassifier.cs, VisualRust/RustTokenTypes.cs, VisualRust/Utils.cs
We are cheating a bit with types exported by prelude, but this looks better for 99% code out there
=> Add highlighting for primitives and preluded types

VisualRust/Racer/RacerSingleton.cs, VisualRust/RustCompletionSource.cs, VisualRust/RustDocumentListener.cs, VisualRust/RustGoToDefinitionCommandHandler.cs, VisualRust/VisualRust.csproj, VisualRust/VisualRustPackage.cs
I still need to do some cleanup, I'd like to reduce the duplication in some of the logic, the TODOs are what I'd like to figure out how to not duplicate. 
I wasn't able to get racer to find definitions in other files inside my own project. It did find definitions in the std library, and definitions that were in the same file. Not sure what's happening there, but I wanted to post this to see if someone else could try it out.
=> Add rudimentry 'Go To Definition' support

VisualRust.Project/EnvironmentPath.cs, VisualRust.Project/Feature.cs, VisualRust.Project/VisualRust.Project.csproj, VisualRust/Forms/DebuggingDisabledControl.Designer.cs, VisualRust/Forms/DebuggingDisabledControl.cs, VisualRust/Forms/DebuggingDisabledControl.resx, VisualRust/Forms/DebuggingOptionsPage.cs, VisualRust/Forms/DebuggingOptionsPageControl.Designer.cs, VisualRust/Forms/DebuggingOptionsPageControl.cs, VisualRust/Forms/RustOptionsPageControl.designer.cs, VisualRust/VSPackage.Designer.cs, VisualRust/VisualRust.csproj
This covers point 1 and 3 in #149
=> Make debugging options page nicer

VisualRust/RustGoToDefinitionCommandHandler.cs, VisualRust/Utils.cs
This should work with files that are unsaved, yet still find the right definition.
=> Make "Go To Definition" work on project files

VisualRust.Templates/VisualRust.Templates.csproj, VisualRust/VisualRust.csproj
On my configuration, fields of RustLexer determined correctly in VS2015 in comparison with VS2013. May be it helps someone else.
=> Small upgrade projects to convenient loading VisualRust in Visual Studio 2015

Microsoft.VisualStudio.Project/Microsoft.VisualStudio.Project.csproj, Microsoft.VisualStudio.Project/ProjectReferenceNode.cs, Microsoft.VisualStudio.Project/app.config, Microsoft.VisualStudio.Project/packages.config, RustLexer/RustLexer.csproj, VisualRust.Build/VisualRust.Build.csproj, VisualRust.Project/RustProjectNodeProperties.cs, VisualRust.Project/VisualRust.Project.csproj, VisualRust.Project/app.config, VisualRust.Project/packages.config, VisualRust.Shared/VisualRust.Shared.csproj, VisualRust.Templates/VisualRust.Templates.csproj, VisualRust.Test.Integration/VisualRust.Test.Integration.csproj, VisualRust.Test.Integration/app.config, VisualRust.Test.Integration/packages.config, VisualRust.Test/VisualRust.Test.csproj, VisualRust.Test/app.config, VisualRust/VisualRust.csproj, VisualRust/VisualRustPackage.cs, VisualRust/app.config
As mentioned in #171 and #173, this PR moves us to managing VSSDK dependencies using [vsxdeps](https://github.com/tunnelvisionlabs/vsxdeps). This makes us compatible with both VS2013 and VS2015.
=> Move dependencies to vsxdeps

Microsoft.VisualStudio.Project/Properties/AssemblyInfo.cs, RustLexer/Properties/AssemblyInfo.cs, VisualRust.Build/Properties/AssemblyInfo.cs, VisualRust.Project/DefaultRustLauncher.cs, VisualRust.Project/Properties/AssemblyInfo.cs, VisualRust.Setup/VisualRust.wxs, VisualRust.Shared/Properties/AssemblyInfo.cs, VisualRust.Templates/Properties/AssemblyInfo.cs, VisualRust/Guids.cs, VisualRust/Properties/AssemblyInfo.cs, VisualRust/VisualRust.csproj, VisualRust/VisualRust.vsct, VisualRust/VisualRustPackage.cs, VisualRust/source.extension.debug.vsixmanifest, VisualRust/source.extension.release.vsixmanifest
During porting our gdb support to MIEngine source builds I accidentally omitted support for showing debuggee's console and didn't port Visual Studio command to interact with gdb. This PR brings them back.
=> Bump version to 0.1.1 and fix various gdb regressions

VisualRust.Shared/Environment.cs, VisualRust/VSCommandTarget.cs
This mitigates the symptoms of issue #181 
Maybe we need another fix to actually load the package even for non-Rust projects? I'm not sure if that's possible / desirable. But at least with this fix Rust files are editable from other kinds projects, syntax highlighting also works...
=> Avoid null ref exception when package is not loaded

VisualRust.Test.Integration/VisualRust.Test.Integration.csproj
I have half of tests failing without this change, and all passing with it... Could be a fix for issue #178.
=> Make all integration tests pass with VS 2015, Win10

VisualRust.Build/Rustc.cs, VisualRust.Project/Launcher/LauncherEnviroment.cs, VisualRust.Shared/Environment.cs
This slightly changes the way we look for target triple supported by a compiler: we simply parse output of `rustc.exe -Vv` instead of sniffing folders. This works the same for official installer < 1.6, official installer >= 1.6 and multirust.
Previous solution was useful for cross-compiling, but I've never really tested it and I don't think anyone uses it with Visual Rust.
=> Add multirust support

VisualRust/VisualRustSmartIndent.cs
This uses the DocumentState for each given ITextBuffer to retrieve relevant tokens. It could probably be further improved to get rid of the TextSnapshot in general and rely entirely on the cached tokens. That would take a bit more refactoring/testing. I think this resolves #94.
=> Use DocumentState for indentation tokens

VisualRust.Shared/Environment.cs, vist_toml/src/lib.rs
- Dropflags no longer exist
- Multirust is now `rustup.rs` and uses different directories. I left the old Multirust code in there and just added another option.
=> Fixes for using recent nightly and rustup.rs

VisualRust.Test/Cargo/ManifestTests.cs, VisualRust.Test/VisualRust.Test.csproj, VisualRust.sln
... by removing unused VisualRust.Cargo project from solution
This is supposed to be only a temporary workaround. The debug build can't be fixed
without changing the AppVeyor configuration, which is unfortunately not checked in as YAML.
=> Try to temporarily fix CI release build

VisualRust.Build/CargoBuild.cs, VisualRust.Build/CargoClean.cs, VisualRust.Build/Rustc.cs, VisualRust.Shared/Cargo.cs, VisualRust.Shared/Environment.cs, VisualRust/Racer/RacerSingleton.cs
Racer, rustc and cargo use UTF8 console output. Fix some problem with non ASCII path to tools.
=> Added UTF8 encoding to process start information for rust tool

VisualRust/Forms/RustOptionsPage.cs, VisualRust/Forms/RustOptionsPageControl.cs, VisualRust/Forms/RustOptionsPageControl.designer.cs, VisualRust/Racer/RacerSingleton.cs, VisualRust/RustGoToDefinitionCommandHandler.cs
Added options for enable rust source auto discovery through `--print sysroot` commad
=> Sysroot for rust src
